# Generated by Django 3.2.9 on 2021-12-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='title',
            new_name='name',
        ),
    ]
