# Generated by Django 3.2.9 on 2021-12-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forta', '0002_rename_title_company_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Company_list',
        ),
    ]
