# Generated by Django 3.2.9 on 2021-12-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forta', '0004_company_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_info',
            name='daily',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='trend',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
