# Generated by Django 3.2.9 on 2021-12-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forta', '0005_auto_20211206_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_info',
            name='logo',
            field=models.CharField(default='https://i.pinimg.com/originals/2a/3c/90/2a3c90c0101bbd853a764e6c15ef811b.jpg', max_length=200),
        ),
    ]
