# Generated by Django 3.2.9 on 2021-12-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forta', '0006_company_info_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticker', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=200)),
                ('Last_Price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Description', models.CharField(max_length=200)),
                ('Logo_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker_Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticker', models.CharField(max_length=200)),
                ('Sector', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Company_info',
        ),
        migrations.DeleteModel(
            name='Company_list',
        ),
    ]
