# Generated by Django 3.2.9 on 2021-12-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forta', '0007_auto_20211209_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker_information',
            name='Logo_url',
            field=models.CharField(default='https://mir-cdn.behance.net/v1/rendition/project_modules/1400_opt_1/97795951247333.58e6f2888bb50.jpg', max_length=200),
        ),
    ]
