# Generated by Django 3.2.9 on 2021-12-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forta', '0008_alter_ticker_information_logo_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticker_Information',
        ),
        migrations.DeleteModel(
            name='Ticker_Sector',
        ),
    ]
