# Generated by Django 3.2.9 on 2021-12-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='tickets',
            new_name='tickers',
        ),
    ]
