Update_log = "LOG | UPDATE: "
Error_log = "LOG | ERROR: "
Open_error_log = "LOG | Cannot open: "
Open_position_log = "LOG | OpenPosition: "
Close_position_log = "LOG | ClosePosition: "
Close_error_log = "LOG | Cannot close: "